#!/bin/sh

if [ $# != 1 ]; then
	echo "usage: $0 <eclipse path>"
	echo
	exit 1
fi

epath=$1
dir=`dirname $0`

if [ -x "$epath/eclipse" -a -f "$epath/icon.xpm" ]; then
	cp -v $dir/eclipse.desktop ~/Desktop/eclipse.desktop
	sed -i "s:_EPATH_:$epath:" ~/Desktop/eclipse.desktop
else
	echo "Invalid eclipse path ($epath)!"
fi

echo
