#!/usr/bin/env python3

import os
from optparse import OptionParser
import re
import shutil
import subprocess
import platform

os_type = platform.system()
if os_type != 'Linux':
    print(os_type + ' NOT supported!')
    exit(1)

if os.getuid() != 0:
    print('must run as super user!')
    exit(1)

dist_serial = {}
for dist in ['RHEL', 'CentOS', 'Fedora', 'OL', 'Rocky', 'AlmaLinux']:
    dist_serial[dist] = 'redhat'
for dist in ['Ubuntu']:
    dist_serial[dist] = 'ubuntu'
for dist in ['Debian', 'Steam OS']:
    dist_serial[dist] = 'debian'
# for dist in ['ARCH_']:
#     dist_serial[dist] = 'archlinux'

def blk_tag(tag, dev):
    fd = os.popen('blkid -s {} {}'.format(tag, dev))
    # r = subprocess.check_output(['blkid', '-s', tag, dev])
    for line in fd:
        kv = line.strip().split('=')
        if len(kv) > 1:
            return kv[1].strip('"')
    return None

def linux_dist(iso):
    label = blk_tag('LABEL', iso)
    if label == None:
        return None
    for dist in dist_serial:
        if label.startswith(dist):
            return dist_serial[dist]
    return None

parser = OptionParser()
parser.add_option('-i', '--isopath', dest='isopath',
                  help='path to ISO image')
parser.add_option('-m', '--volume', dest='volume',
                  help='mount point')
# parser.add_option('-d', '--drive', dest='drive',
#                   help='mount point')

(opts, args) = parser.parse_args()

if opts.isopath != None:
    repo = opts.isopath
else:
    repo = os.getcwd()

if opts.volume == None:
    parser.print_help()
    exit(1)

root = re.sub('/+$', '', opts.volume)
part = ''

if root == '' or not os.path.exists(repo):
    parser.print_help()
    exit(1)

for line in open('/proc/mounts').readlines():
    mnt = line.split()
    if root == mnt[1]:
        part = mnt[0]
        break
if part == '':
    print('No such mount point:', root)
    exit(1)

uuid = blk_tag('UUID', part)

# FIXME: sdXN, mmcMpN, nvmeMnNpX
disk = re.sub('\d+$', '', part)
index = part[len(disk):]

boot_dir = root + '/boot'
iso_dir  = root + '/iso'

for d in [boot_dir, iso_dir]:
    if not os.path.exists(d):
        os.mkdir(d)

# ############### copy ISO ###############
print('Copying ISO ...')

if os.path.isdir(repo):
    src_list = []
    for iso in os.listdir(repo):
        if iso.endswith('.iso'):
            iso = repo + '/' + iso
            if linux_dist(iso) != None:
                src_list.append(iso)
            else:
                print('"{}" skipped'.format(iso))
    if len(src_list) == 0:
        print('No valid Linux ISO found in "{}"!'.format(repo))
        exit(1)
elif os.path.exists(repo) and linux_dist(repo) != None:
    src_list = [repo]
else:
    print("'{}' is invalid!".format(repo))
    exit(1)

iso_list = []
count = 0
for iso in src_list:
    count += 1
    bname = os.path.basename(iso)
    print(f'[{count}/{len(src_list)}] ', end='')

    dest_iso = iso_dir + '/' + bname

    if os.path.exists(dest_iso):
        print(dest_iso + ' already exists!')
    else:
        print(f'{bname} -> {iso_dir} ...')
        shutil.copyfile(iso, dest_iso)

    iso_list.append(dest_iso)

############# install grub #############

print('\nInstalling Grub ...')

grub_cfg = None
for grub in ['grub', 'grub2']:
    grub_cmd = grub + '-install'
    if shutil.which(grub_cmd) != None:
        grub_cfg = boot_dir + '/' + grub + '/grub.cfg'
        break

if grub_cfg == None:
    print('No grub installer found!')
    exit(1)

pttype = blk_tag('PTTYPE', disk)
# print(f'{disk}: {pttype}')

march = platform.machine()
# TODO: machine string mapping

if pttype == 'gpt':
    grub_cmd += f' --target={march}-efi'

    esp = None
    fd = os.popen('parted ' + disk + ' print')
    for line in fd:
        fields = line.strip().split()
        if len(fields) > 0 and fields[0].isdigit() and 'esp' in fields:
            esp = fields[0]
            break
    if esp == None:
        print("ESP partition not found!")
        exit(1)

 #   for _part in os.listdir('/dev'):
 #       _part = '/dev/' + _part
 #       if re.match(disk + '\d+', _part): # or + '\d+p\d+'
 #           subprocess.call(['umount', _part])

    efi_dir = boot_dir + '/efi'
    if not os.path.exists(efi_dir):
        os.mkdir(efi_dir)
    subprocess.call('mount {}{} {}'.format(disk, esp, efi_dir), shell=True)
else:
    grub_cmd += f' --target={march}-pc'

for g in ['grub', 'grub2']:
    grub_dir = boot_dir + '/' + g
    if os.path.exists(grub_dir):
        shutil.rmtree(grub_dir)

grub_cmd += f' --removable --boot-directory={boot_dir} {disk}'
print(grub_cmd)

try:
    subprocess.call(grub_cmd, shell=True)
except Exception as e:
    print(e)
    if not os.path.exists('/sys/firmware/efi'):
        print('Did you forget to install grub-efi?')

print(f'Generating {grub_cfg} ...')

configs = ['GRUB_TIMEOUT=5',
    'insmod ext2',
    'insmod all_video'
]

if pttype == 'gpt':
    configs.append('insmod part_gpt')

count = 0
for iso in iso_list:
    label = blk_tag('LABEL', iso)
    iso_rel = iso[len(root):]

    count += 1
    print(f'[{count}/{len(iso_list)}] {label} ({iso_rel})')

    menuentry = [
        f"menuentry 'Install {label}' {{",
        '\tsearch --no-floppy --fs-uuid --set=root ' + uuid,
        '\tloopback lo ' + iso_rel
        ]

    dist = linux_dist(iso)

    if dist == 'redhat':
        linux=f'isolinux/vmlinuz inst.repo=hd:UUID={uuid}:/iso'
        initrd='isolinux/initrd.img'
    elif dist == 'ubuntu':
        linux='casper/vmlinuz boot=casper iso-scan/filename=' + iso_rel
        initrd='casper/initrd'
    elif dist == 'debian':
        menuentry.append('\tset isofile=' + iso_rel)
        linux='install.amd/vmlinuz'
        initrd='install.amd/initrd.gz'
    else:
        print(f'Warning: "{iso}" NOT supported(skipped)!')
        continue

    # FIXME
    linux += ' modprobe.blacklist=nouveau'

    menuentry.append("\tlinux (lo)/" + linux)
    menuentry.append("\tinitrd (lo)/" + initrd)
    menuentry.append("}")

    configs += menuentry

cf = open(grub_cfg, 'w')
for line in configs:
    cf.write(line + '\n')
cf.close()

if pttype == 'gpt':
    subprocess.call('umount {}/efi'.format(boot_dir), shell=True)
