#!/bin/sh

if [ $# != 1 ]; then
	echo "usage: $0 <eclipse path>"
	echo
	exit 1
fi

dir=`dirname $0`
epath=$1

if [ -f "$epath" ]; then
    epath=$(dirname "$epath")
fi

if [ -x "$epath/eclipse" -a -f "$epath/icon.xpm" ]; then
	sed "s:_EPATH_:$epath:" $dir/eclipse.desktop > ~/Desktop/eclipse.desktop
	chmod +x ~/Desktop/eclipse.desktop
else
	echo "Invalid eclipse path ($epath)!"
fi

echo
