#!/bin/sh

if [ $# == 1 ]; then
	user="admin" # or $USER
	pass="maxwit"
	dbname=$1
elif [ $# == 3 ]; then
	user=$1
	pass=$2
	dbname=$3
else
	echo -e "Usage: $0 [user] [password] <dbname>\n"
	exit 1
fi

dbms=(${0//-/ })
dbms=${dbms[1]}
#host='localhost'

tmp=`mktemp`.sql

case $dbms in
	mysql|mariadb)
# FIXME
# create user IF NOT EXISTS $user identified by '$pass';
cat > $tmp << _EOF_
create user $user@'localhost' identified by '$pass';
\q
_EOF_
	cat $tmp
	mysql -uroot -pmaxwit -Dmysql < $tmp

cat > $tmp << _EOF_
create database if not exists $dbname character set=utf8;
grant all on $dbname.* to $user@'localhost';
_EOF_
	cat $tmp
	mysql -uroot -pmaxwit -Dmysql < $tmp

	echo "status" | mysql -u$user -p$pass -D$dbname
	;;

	psql|pgsql|postgresql)
cat > $tmp << _EOF_
create user $user with password '$pass';
create database $dbname encoding='utf8' owner=$user;
_EOF_
	psql -Upostgres < $tmp

	echo '----------------------'
cat > $tmp << _EOF_
\conninfo
\encoding
_EOF_
	psql -U$user -d$dbname < $tmp
	;;

	*)
	echo "$dbms not supported yet!"
	exit 1
	;;
esac

echo
