#!/bin/bash

repo=$1
repo=${repo#/home/git/repositories/}
repo=${repo%.git/refs/heads}

clone_repo()
{
	cd

	if [ -d $1 ]; then
		cd $1
		git pull
	else
		git clone git@192.168.1.1:$1.git $1
		cd $1
	fi

	make
}

case $repo in
book/*|book/*|testing/*)
	clone_repo $repo

	if [ $# -eq 2 ]; then
		dest=$2/$repo
		mkdir -p $dest
		cp -v *.pdf $dest
	fi
	;;

project/*)
	clone_repo $repo
	;;
esac
